spring:
  datasource:
    url: jdbc:mysql://mysql2.sqlpub.com:3307
    username: ororigin
    password: iPOAZ4gXe78sSeAI
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # 生产建议 validate，开发可使用 update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  sql:
    init:
      mode: always  # 首次运行可自动执行 schema.sql / data.sql

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.library: debug